language: python

dist: xenial

sudo: true

addons:
  apt_packages:
    - libcups2-dev

services:
  - mysql

install:
  - pip install --upgrade pip
  - pip install flake8 coverage codecov tox-travis

before_script:
  - flake8 django_collect_offline
  - mysql -e 'create database edc_default character set utf8;'
  - mysql -e 'create database edc_server character set utf8;'
  - mysql -e 'create database edc_client character set utf8;'
  - mysql -e 'create database edc_test_server character set utf8;'

script:
  - coverage run -m tox

after_success:
  - codecov

matrix:
  include:
    - python: 3.7
      env: TOXENV=py37-django22
;    - python: 3.7
;      env: TOXENV=py37-djangotrunk
